# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10:
        CONFIG: win_64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11:
        CONFIG: win_64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp312python_impl_version3.12python_implementationcpythonpython_version3.12:
        CONFIG: win_64_python_abi_tagcp312python_impl_version3.12python_implementationcpythonpython_version3.12
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp313python_impl_version3.13python_implementationcpythonpython_version3.13:
        CONFIG: win_64_python_abi_tagcp313python_impl_version3.13python_implementationcpythonpython_version3.13
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp313tpython_impl_version3.13python_implementationcpythonpython_version3.13:
        CONFIG: win_64_python_abi_tagcp313tpython_impl_version3.13python_implementationcpythonpython_version3.13
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8:
        CONFIG: win_64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9:
        CONFIG: win_64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_taggraalpy230_310_nativepython_impl_version23.0python_implementationgraalpypython_version3.10:
        CONFIG: win_64_python_abi_taggraalpy230_310_nativepython_impl_version23.0python_implementationgraalpypython_version3.10
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_taggraalpy231_310_nativepython_impl_version23.1python_implementationgraalpypython_version3.10:
        CONFIG: win_64_python_abi_taggraalpy231_310_nativepython_impl_version23.1python_implementationgraalpypython_version3.10
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8:
        CONFIG: win_64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8
        UPLOAD_PACKAGES: 'True'
      win_64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9:
        CONFIG: win_64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9
        UPLOAD_PACKAGES: 'True'
    maxParallel: 8
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:

    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)